<?php

namespace Pristo\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function findForAdmin($start, $limit){
        $qb = $this->createQueryBuilder("a")
                ->setFirstResult($start)
                ->setMaxResults($limit)
                ->getQuery();            
        try{
            $authors = $qb->getResult();            
        }catch (\NoResultException $e){
              throw new UsernameNotFoundException(
                        sprintf('Unable to find an active admin PristoFrontBundle:User object identified by "%s".', $name),
                        null, 0, $e);        
        }
        return $authors;
    }
    
    public function maxPage($max){
        $users = $this->findAll();        
        return floor(count($users) / $max);
    }
    
}
