<?php

namespace Pristo\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedRepository extends EntityRepository
{
    public function findWithCartsList($status, $start, $limit){                        
        if($status == 0){                        
            $qb = $this->createQueryBuilder("o")
                ->leftJoin("o.carts", "c")
                ->leftJoin("o.userId", "u")
                ->leftJoin("o.addressId", "a")
                ->orderBy("o.updated", "DESC")
                ->setFirstResult($start)                
                ->setMaxResults($limit)
                ->getQuery();
        }else{
            $qb = $this->createQueryBuilder("o")
                ->innerJoin("o.carts", "c")
                ->innerJoin("o.userId", "u")
                ->leftJoin("o.addressId", "a")
                ->where("o.isEnabled = 1")
                ->andWhere("c.isEnable = 1")
                ->andWhere("u.isEnabled = 1")
                ->andWhere("o.status = :status" )
                ->orderBy("o.updated", "DESC")
                ->setParameter("status", $status)
                ->setFirstResult($start)
                ->setMaxResults($limit)
                ->getQuery();
        }
        
        try{            
            $result = $qb->getResult();
        }catch (\NoResultException $e){
            return null;
        }
                
        
        return $result;
    }
    
        
    public function maxPage($status, $max){
        if($status ==0 ){
            $ordered = $this->findAll();
        }else{
            $ordered = $this->findByStatus($status);            
        }
        return floor(count($ordered) / $max);
    }            
}
