<?php

namespace Pristo\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findForView($page){
        
        $rankings = $this->buyRanking($page, $page+self::PAGE_ITEMS);        
        
        
        
        foreach($products as &$product){
            $product->totalBuyed = $totalBuyed[$product->getId()];
            
        }
        
        return $products;
        
    }
     
    
    public function buyRanking($start, $end){
        $qb = $this->createQueryBuilder('p')
                ->select("p.id, a.name")
                ->addSelect("SUM(i.buyed) as totalBuyed")
                ->leftJoin("p.authorId", "a")
                ->innerJoin("PristoAdminBundle:Items", "i", "WITH", "i.productId = p.id")
                ->groupBy("p.id")
                ->orderBy("totalBuyed", "DESC")
                ->setFirstResult($start)
                ->setMaxResults($end)
                ->getQuery();
        try{
            return $qb->getResult();
        }  catch (\NoResultException $e){
            return null;
        }
        
    }
    
    public function getMaxNum($authorId){
        $products = $this->findByAuthorId($authorId);
         return count($products);
    }
        
}
